- name: get windows ad details
  hosts: '*windows_ad'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - debug:
        var: hostvars[inventory_hostname]

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          dns_servers:  "{{ ansible_ip_addresses[0] | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: dns_servers

- name: prereqs
  hosts: '*cluster_first:*cluster_other'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  pre_tasks:
    - debug:
        var: dns_servers
  roles:
    - domain
    - iis-dsc
    - role: failover-cluster-common

- name: Create failover cluster on first node
  hosts: '*cluster_first'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: failover-cluster
      first_node: yes

- name: Join failover clusters on other nodes
  hosts: '*cluster_other'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: failover-cluster
      first_node: no
