- name: get windows ad details
  hosts: '*windows_ad'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: set ad server ip
      add_host:
        name: windows_ad_server
        ip_address:  "{{ ansible_ip_addresses[0] | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: hostvars['windows_ad_server']['ip_address']

- name: prereqs
  hosts: '*cluster_first:*cluster_other'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  pre_tasks:
    - name: set ip address of windows ad
      set_fact:
        dns_servers: "{{ hostvars['windows_ad_server']['ip_address'] }}"
      when:
        - "'windows_ad_server' in play_hosts"
        - hostvars['windows_ad_server']['ip_address'] is defined
  roles:
    - domain
    - iis-dsc
    - failover-cluster-common

- name: Create failover cluster on first node
  hosts: '*cluster_first'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: failover-cluster
      first_node: yes

- name: Join failover clusters on other nodes
  hosts: '*cluster_other'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: failover-cluster
      first_node: no